ptf #
Channel Parameters
StreamOrder
10,1,  'Bw     HLINK   ChSSlp   MannN'
1,     1.6,    0.02,   0.03,    # MannN1 #
2,     2.4,    0.02,   0.03,    # MannN2 #
3,     3.5,    0.02,   0.03,    # MannN3 #
4,     5.3,    0.03,   0.04,    # MannN4 #
5,     7.4,    0.03,   0.04,    # MannN5 #
6,     11.,    0.03,   0.04,    # MannN6 #
7,     14.,    0.03,   0.04,    # MannN7 #
8,     16.,    0.10,   0.04,    # MannN8 #
9,     26.,    0.30,   0.05,    0.02
10,    110.,    0.30,   0.10,   0.02
