ptf #
Fulldom_hires pars to be modified by PEST. File created to interface with PEST. Used to modify nc file Fulldom_hires.nc.
The code to create the netcdf file is set up to read this file line by line. Deleting these first two lines will break it. Other params can be added in the same format as below
LKSATFAC
3,  # lksatfac3 #,  6,  # lksatfac6 #,  7,  # lksatfac7 #,  9,  # lksatfac9 #,  12,  # lksatfac12 #
