#!/bin/bash
#PBS -N sl_slave_no
#PBS -l ncpus=48
#PBS -l mem=190GB
#PBS -l walltime=48:00:00
#PBS -q normal
#PBS -l storage=gdata/w97+gdata/hh5+gdata/w28
#PBS -W umask=0022
#PBS -j oe

echo $PATH
export PATH="$PATH:/home/566/ad9701/bin/"

echo PBS_O_WORKDIR=$PBS_O_WORKDIR
cd $PBS_O_WORKDIR

export islave=slave_no
cd test${islave}
pwd
#echo "../run_hydro_slave.sh" | pslave
echo "../run_hydro_slave_modSoilClass.sh" | pslave
#echo "../run_hydro_slave_modTopo.sh" | pslave
