#!/bin/bash

#PBS -P w97
#PBS -q normal
#PBS -l walltime=03:00:00
#PBS -l mem=190GB
#PBS -l ncpus=1
#PBS -l storage=gdata/w97+gdata/hh5+gdata/w28+scratch/w97
#PBS -m a
#PBS -M anjana.devanand@unsw.edu.au
#PBS -N seasonal_calc
#PBS -l wd

# used 48GB for 4km
# 128GB or 190GB for 1km
# 32GB for 10km

module use /g/data/hh5/public/modules
module load conda/analysis3

export wrf_hydro_dir

python ~/wrf_hydro/calc_seasonalmean_savenc_fromaccum.py
