#!/bin/bash

#PBS -P w97
#PBS -q normalbw
#PBS -l walltime=00:30:00
#PBS -l mem=32GB
#PBS -l ncpus=1
#PBS -l storage=gdata/w97+gdata/hh5+gdata/w28+scratch/w97+scratch/w28
#PBS -m a
#PBS -M anjana.devanand@unsw.edu.au
#PBS -N dailymax_calc
#PBS -l wd

#####PBS -j oe
#####PBS -l wd

# walltime for all land grids = 45:00:00
# also removed jobfs PBS -l jobfs=50gb

module use /g/data/hh5/public/modules
module load conda/analysis3

export WRF_HYDRO_DIR=/g/data/w97/ad9701/WRF-Hydro/SEA/noGW_runs/runs_wCalibPars_10km/wrf_hydro_nwm_public-5.2.0_domain4_10km_monPnTCorr_t80_RTCHon_defSoil_defPar/trunk/NDHMS/Run/
export varname=T2M

python ~/wrf_hydro/calc_daily_max.py
