#!/bin/bash

#PBS -P w28
#PBS -q normalbw
#PBS -l walltime=00:30:00
#PBS -l mem=16GB
#PBS -l ncpus=1
#PBS -l storage=gdata/w97+gdata/hh5+gdata/w28+scratch/w97+scratch/w28
#PBS -m a
#PBS -M anjana.devanand@unsw.edu.au
#PBS -N hrly_to_daily
#PBS -l wd

#####PBS -j oe
#####PBS -l wd

# walltime for all land grids = 45:00:00
# also removed jobfs PBS -l jobfs=50gb

module use /g/data/hh5/public/modules
module load conda/analysis3

export WRF_HYDRO_DIR=/scratch/w97/ad9701/WRF-Hydro/SEA/noGW_runs/runs_wCalibPars_1km_167mRT/wrf_hydro_nwm_public-5.2.0_domain4_1km_t80_RTCHon_monPnTCorr_defSoil_defPar/trunk/NDHMS/Run/
export year=2018
export mon=1
export day=1

python ~/wrf_hydro/concat_hourly_files_to_daily.py
