#!/bin/bash

#PBS -P w97
#PBS -q normalbw
#PBS -l walltime=00:30:00
#PBS -l mem=16GB
#PBS -l ncpus=1
#PBS -l storage=gdata/w97+gdata/hh5
#PBS -m a
#PBS -M anjana.devanand@unsw.edu.au
#PBS -N hrly_to_daily
#PBS -l wd

#####PBS -j oe
#####PBS -l wd

# walltime for all land grids = 45:00:00
# also removed jobfs PBS -l jobfs=50gb

module use /g/data/hh5/public/modules
module load conda/analysis3

export WRF_HYDRO_DIR
export year
export mon
export day

python ./concat_hourly_files_to_daily.py
